apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shifa-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salsabiilashifa11/argocd-app-config.git
    targetRevision: HEAD
    path: src
  destination:
    server: https://kubernetes.default.svc
    namespace: shifa-application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true